language: ruby
rvm:

  # this is close to what we got in the VM:
  - 1.26.10

  - 1.9.2
  - 1.9.3
env:
  # empty
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake test
  #- bundle exec rspec spec/
