language: ruby
rvm:
  - 1.9.3
env:
  - RAILS_ENV=test
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake test_with_coveralls
notifications:
  email:
    recipients:
      - serler2ci@eemaill.org
